language: node_js
node_js:
- 12
services:
- postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "grace-shopper-team-f-test";' -U postgres
script:
- npm test
- webpack
branches:
  only:
  - master
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app:
    master: grace-shopper-team-f
  api_key:
    secure: feXqGrvYKP80D6w3zWmbrRv5GIERAZkkF5xc5Mf+J21hHnYo/IDGeseDb5vUIPrBo6nD/zlScaZhohZRPEx1K6PsemziNMc2ONhE5jGn9UbMMVSxlzFR/RHF/MPrEK29zWit4/Y048PMd8Ha5ny35F4pcSkQg8v9qKe+4Z5VI6V4sVfI9RgyedHy2VhtY3eYIpRbOCHS5nrmuCRSeVrw/BZAZZ/vNwjyQi2gkzVMK/Cmb4XlJpP/N/55D1hl/4xjnrBz6C1p7Ft3jnDnJ0hlp/UEDEio/23HsSN0soGc6pWXBI1Xl38d6qvKAKRq8n1BG6WjlOOjI8IWAIldgcd/XRE9XEdGdKnNBT5FHDsPL15mnwza8tbkDhiOwyc6vP4w++C//N7OBx0dZ4MwO7bTNK7nGrTIZ2Gv62JL/L1SH9FamK1Po4T3B6tQHXCr7bEa5rUW0V49BcW7zdmrF2Z8mXbJHZLduOdSYBZzPjnL5fZkbTh7tf2iIQLENqmV2W37OEjix91q+j0J6W2IZknl3PDEMlbeFSnFt/yj4vMA1PRQ69vy91TXMMzOnvAgCbm4InAXRgtorU4Iz2UoDbwTDtglIJuzPdBgJ3nsFh7ghR3k93j6FBablKiarqLbTk567iWtVii1WwURzwqAH8ixgrNzQ5cw0Lv1arO5Tg9hfbU=
env:
  global:
    SESSION_SECRET:
      secure: fe6+D6pSNkTdE0M7urTpaQmIAoKnyWjkgvs20uuUKmGCylqZReQz0YO9CRYaBsycFial8EWfdqYbJpbO9vWAAS7765bfqfbBtY+wKSmG7OWWriTwxQ7SR2W/ycIgFFog9kHaA+fSCq+eWozlnDgPVzJkhJ4jzURKDHPLVpkph5ax3x0YF/r7BApD5zzdr+2iLYkE67QpVkxKQVJLALgWeYNnkN85T3H2vAXV7pis2aEhjFbhg4U7h44vtComwbyK2Lg2n8gvKAHcHuq7ECRVOZ/E5ifBriZFd/L0NB/k63NYGEph0G2qyg3Pr8WJoNole5kcgycauB57phLEKe6PVZ9TdqFQOU839eL7lAy15/ZXUg7DxaymcVREJpBAlLCXpdQClDxRvNg/Npri11zZqiIjj6isIftgsX6wUpkYYF2xcCtjJFcosPlRu6xNqfQhy/PC+LKUt1tZOhRXZv+OSrHwx8ZfUp+Qv/h1hixMbQXlr+/ehm6MIcqb68UTjNu5H0JKvW1KgQ/N+4szKfotcqBjgDaLoeb9nm0+WLPoDmEPlZdsHbUbIjHJJTovGZMBJ5bgbXS7ILg4PNHdlnlAGE6pZwsfj2Anv+0WYJUemhLHkyXC1wdos5bQXQyiXQm/zX96gLEiOEuopR6akbEMSvB3SyCtNhJ7DYgngIGC8dQ=
    GOOGLE_CLIENT_ID:
      secure: G0VB4EPJTnK4stZiQh3zHsOZpas0+OEvWGQulMuQMqMyHd+g2rLwzGRcijYt9VfcfGHkX8GJyUbxSItab4QHQKitq7S0KUanGFIAbKHdacec0Q1tCX4NCaMLUFJRnqZ++7AYGP7/jIahqjzQBkYAdb5gaUD7OOBeSCR/HEj70WClgascCiscvSKJpob3lIjN1JF1rbjIAYuts61ZHssBxvX3APmsI+AmCAbansVc105vioLe60LF7lX++8MnlRT0I0t/1IEoBwmxZfw4vVA2lndPc3nRqZ/+EPyLScUMnkJlk/tHlbZhvH48iKAs/fH2IomeVcm3EvVG3jbpmPrL5wg//pPZTJ1MS6dfzpL0/ovo0ccmosdmnmXOXQE7IoEgEiCYPQ0z5JAc1itXI+FBz2uDuGAX1LzMbQBCkUd0LXIhw09KeAmqlEXS9Ay2TCqfuc+Yi99e7lbP1YFp4ZtMF4/US+r1ZmBsRrVUY0Ntek1LA/T2Nyiua/cyZmDXJ67nzObcooTY++fUjeFl+Ate+3FR10dNZJtNCJSQ3OjAkmjBf4utLMtC6CFb2h5zdQlno4T+0S6sJn5ryRWdLdjIDY5nvhW/dC5M0dlJ6RjxFQfi5k/VfbjLN8y3nluWVSLq/Bv5OAzAhkqYI1SobUCAxGpIyjeKBxlXrqXeW5BVmac=
    GOOGLE_CLIENT_SECRET:
      secure: ziuIXxWRpaWxVmRWElG6sdwCdaBAgXlNTAeQJwcCJYC9lKnW6IssdAgUVGZyLBJOGpIV4VloUAmW5GqF2Fq7Qir3C73OzJCdFHbLfwOQKTSBlSt2RL3tBP5DQdwqDeTdrCtaphZsiySumABlliMHvZtm+rS1aQG1I3mGL1L2SZBu9Rtjs6SFTA301xaRHn7C2YQigHlJgwbfjspRwAZVErYMY1zcgbrjUSlZfNRVpqsbWzqqXI/i9rnlgxKdxiwK4lzpee/dXBIhKU7DXGB62U9dnHvENNzQRi+IzlwRhFBNzulk+FJm7Ae4ocKF9Q0GEIqAibV3phwc7BdPB/ooZ4Z6QRn5mTupKcSeStQf0m3iPY3v9LqxX960QsawaRDaLxWfGLovYqwLw74GcL4SHQu5etcsDSCkfiWHcHJkZMyjuQpQjwXcZXm0pMAkWwcnsDXxvspvL3BbLLyomJ7uiNrTTaSqqrNbCBN67UkyxmC1lHkukoAqMNzoAXihDyo1zcyhz6tiBSbZVk+9d6P1n41HzGgKt9mRHpZIMORo37zmxQlUvUjqgHQcY6ZqT9vHI6ZNXbVBAmM7+b2aSWnJZiQfyPFfe1sx0yWPYdmiAi+UE9TdZiJtWo/NwH1fEnMGcLr+NCri+XT7DZVmTTGtfQyPKrEK4e8zKRp8Iqsm5QQ=
